- hosts: amazon
  remote_user: ec2-user 
  become: yes
  tasks:
    - name: im going to install 3 package using loop
      yum: 
        name: "{{ item }}"
        state: present
      loop:
        - mysql
        - nginx
        - php
